name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF >>test.txt
          test
          test
          EOF
