name: CI

on:
  workflow_dispatch:

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - run: ip r  | grep default | awk -F' ' '{print $5}'
      id: default_if
    
#     - name: Install virtualbox
#       run: sudo apt-get update && sudo apt-get install virtualbox
      
    - run: echo ${{ steps.default_if.outputs.stdout }}
