name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  translations:
    runs-on: macos-12
    steps:
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
      
      - run: env
      
      - run: find / -name "*packer.d" 2>/dev/null
      
