name: CI

on:
  workflow_dispatch:

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install virtualbox
      run: sudo apt-get update && apt-get install virtualbox
