name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - name: Get cache
        uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: |
            ./test.txt
          key: ${{ runner.os }}-state
          
      - run: |
          cat <<EOF >>test.txt
          ${{ github.sha }}
          EOF

      - run: cat test.txt
  
      - name: Cleanup cache before save state.json
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH="refs/head/${{ github.ref }}"
          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
          echo $cacheKeys
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache test.txt
        uses: actions/cache/save@v3
        with:
          path: |
            ./test.txt
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
