name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  translations:
    runs-on: macos-12
    steps:
      - run: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage list vms
